/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package flutter_sozler_2

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'flutter_sozler_2.greeting' plugin.
 */
class Flutter_sozler_2PluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("flutter_sozler_2.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
